# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3210c19509b367fdc5b9496dcd082151675cc3847a4dc04016bde4e772a941b20d0948b1e55090094808cb72acee1009ec467107b0bd0039654df743992e1bc3

test:
  secret_key_base: 3129a2346e3421d46cdf2fc57a0ee1e2fefa12923eb7b0b13ae008c4cb4727fd95f02f6d65ed27a30e9639c10cac3325acfe981504a1850ad0110806dc00a338

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
